/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThamDinhRouteImport } from './routes/tham-dinh'
import { Route as HoSoIndexRouteImport } from './routes/ho-so/index'
import { Route as HoSoIdRouteImport } from './routes/ho-so/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThamDinhRoute = ThamDinhRouteImport.update({
  id: '/tham-dinh',
  path: '/tham-dinh',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoIndexRoute = HoSoIndexRouteImport.update({
  id: '/ho-so/',
  path: '/ho-so/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoIdRoute = HoSoIdRouteImport.update({
  id: '/ho-so/$id',
  path: '/ho-so/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tham-dinh': typeof ThamDinhRoute
  '/ho-so/$id': typeof HoSoIdRoute
  '/ho-so/': typeof HoSoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tham-dinh': typeof ThamDinhRoute
  '/ho-so/$id': typeof HoSoIdRoute
  '/ho-so': typeof HoSoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tham-dinh': typeof ThamDinhRoute
  '/ho-so/$id': typeof HoSoIdRoute
  '/ho-so/': typeof HoSoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tham-dinh' | '/ho-so/$id' | '/ho-so/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tham-dinh' | '/ho-so/$id' | '/ho-so'
  id: '__root__' | '/' | '/tham-dinh' | '/ho-so/$id' | '/ho-so/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThamDinhRoute: typeof ThamDinhRoute
  HoSoIdRoute: typeof HoSoIdRoute
  HoSoIndexRoute: typeof HoSoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tham-dinh': {
      id: '/tham-dinh'
      path: '/tham-dinh'
      fullPath: '/tham-dinh'
      preLoaderRoute: typeof ThamDinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so/': {
      id: '/ho-so/'
      path: '/ho-so'
      fullPath: '/ho-so/'
      preLoaderRoute: typeof HoSoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so/$id': {
      id: '/ho-so/$id'
      path: '/ho-so/$id'
      fullPath: '/ho-so/$id'
      preLoaderRoute: typeof HoSoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThamDinhRoute: ThamDinhRoute,
  HoSoIdRoute: HoSoIdRoute,
  HoSoIndexRoute: HoSoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
