/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChiTraRouteImport } from './routes/chi-tra'
import { Route as DanhGiaRouteImport } from './routes/danh-gia'
import { Route as DieuDuongRouteImport } from './routes/dieu-duong'
import { Route as DungCuChinhHinhRouteImport } from './routes/dung-cu-chinh-hinh'
import { Route as HeThongRouteImport } from './routes/he-thong'
import { Route as KhaoSatRouteImport } from './routes/khao-sat'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NghiaTrangRouteImport } from './routes/nghia-trang'
import { Route as PhanTichRouteImport } from './routes/phan-tich'
import { Route as ThamDinhRouteImport } from './routes/tham-dinh'
import { Route as TraCuuRouteImport } from './routes/tra-cuu'
import { Route as HoSoIndexRouteImport } from './routes/ho-so/index'
import { Route as HoSoIdRouteImport } from './routes/ho-so/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiTraRoute = ChiTraRouteImport.update({
  id: '/chi-tra',
  path: '/chi-tra',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhGiaRoute = DanhGiaRouteImport.update({
  id: '/danh-gia',
  path: '/danh-gia',
  getParentRoute: () => rootRouteImport,
} as any)
const DieuDuongRoute = DieuDuongRouteImport.update({
  id: '/dieu-duong',
  path: '/dieu-duong',
  getParentRoute: () => rootRouteImport,
} as any)
const DungCuChinhHinhRoute = DungCuChinhHinhRouteImport.update({
  id: '/dung-cu-chinh-hinh',
  path: '/dung-cu-chinh-hinh',
  getParentRoute: () => rootRouteImport,
} as any)
const HeThongRoute = HeThongRouteImport.update({
  id: '/he-thong',
  path: '/he-thong',
  getParentRoute: () => rootRouteImport,
} as any)
const KhaoSatRoute = KhaoSatRouteImport.update({
  id: '/khao-sat',
  path: '/khao-sat',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NghiaTrangRoute = NghiaTrangRouteImport.update({
  id: '/nghia-trang',
  path: '/nghia-trang',
  getParentRoute: () => rootRouteImport,
} as any)
const PhanTichRoute = PhanTichRouteImport.update({
  id: '/phan-tich',
  path: '/phan-tich',
  getParentRoute: () => rootRouteImport,
} as any)
const ThamDinhRoute = ThamDinhRouteImport.update({
  id: '/tham-dinh',
  path: '/tham-dinh',
  getParentRoute: () => rootRouteImport,
} as any)
const TraCuuRoute = TraCuuRouteImport.update({
  id: '/tra-cuu',
  path: '/tra-cuu',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoIndexRoute = HoSoIndexRouteImport.update({
  id: '/ho-so/',
  path: '/ho-so/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoIdRoute = HoSoIdRouteImport.update({
  id: '/ho-so/$id',
  path: '/ho-so/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chi-tra': typeof ChiTraRoute
  '/danh-gia': typeof DanhGiaRoute
  '/dieu-duong': typeof DieuDuongRoute
  '/dung-cu-chinh-hinh': typeof DungCuChinhHinhRoute
  '/he-thong': typeof HeThongRoute
  '/khao-sat': typeof KhaoSatRoute
  '/login': typeof LoginRoute
  '/nghia-trang': typeof NghiaTrangRoute
  '/phan-tich': typeof PhanTichRoute
  '/tham-dinh': typeof ThamDinhRoute
  '/tra-cuu': typeof TraCuuRoute
  '/ho-so/$id': typeof HoSoIdRoute
  '/ho-so/': typeof HoSoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chi-tra': typeof ChiTraRoute
  '/danh-gia': typeof DanhGiaRoute
  '/dieu-duong': typeof DieuDuongRoute
  '/dung-cu-chinh-hinh': typeof DungCuChinhHinhRoute
  '/he-thong': typeof HeThongRoute
  '/khao-sat': typeof KhaoSatRoute
  '/login': typeof LoginRoute
  '/nghia-trang': typeof NghiaTrangRoute
  '/phan-tich': typeof PhanTichRoute
  '/tham-dinh': typeof ThamDinhRoute
  '/tra-cuu': typeof TraCuuRoute
  '/ho-so/$id': typeof HoSoIdRoute
  '/ho-so': typeof HoSoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chi-tra': typeof ChiTraRoute
  '/danh-gia': typeof DanhGiaRoute
  '/dieu-duong': typeof DieuDuongRoute
  '/dung-cu-chinh-hinh': typeof DungCuChinhHinhRoute
  '/he-thong': typeof HeThongRoute
  '/khao-sat': typeof KhaoSatRoute
  '/login': typeof LoginRoute
  '/nghia-trang': typeof NghiaTrangRoute
  '/phan-tich': typeof PhanTichRoute
  '/tham-dinh': typeof ThamDinhRoute
  '/tra-cuu': typeof TraCuuRoute
  '/ho-so/$id': typeof HoSoIdRoute
  '/ho-so/': typeof HoSoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chi-tra'
    | '/danh-gia'
    | '/dieu-duong'
    | '/dung-cu-chinh-hinh'
    | '/he-thong'
    | '/khao-sat'
    | '/login'
    | '/nghia-trang'
    | '/phan-tich'
    | '/tham-dinh'
    | '/tra-cuu'
    | '/ho-so/$id'
    | '/ho-so/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chi-tra'
    | '/danh-gia'
    | '/dieu-duong'
    | '/dung-cu-chinh-hinh'
    | '/he-thong'
    | '/khao-sat'
    | '/login'
    | '/nghia-trang'
    | '/phan-tich'
    | '/tham-dinh'
    | '/tra-cuu'
    | '/ho-so/$id'
    | '/ho-so'
  id:
    | '__root__'
    | '/'
    | '/chi-tra'
    | '/danh-gia'
    | '/dieu-duong'
    | '/dung-cu-chinh-hinh'
    | '/he-thong'
    | '/khao-sat'
    | '/login'
    | '/nghia-trang'
    | '/phan-tich'
    | '/tham-dinh'
    | '/tra-cuu'
    | '/ho-so/$id'
    | '/ho-so/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChiTraRoute: typeof ChiTraRoute
  DanhGiaRoute: typeof DanhGiaRoute
  DieuDuongRoute: typeof DieuDuongRoute
  DungCuChinhHinhRoute: typeof DungCuChinhHinhRoute
  HeThongRoute: typeof HeThongRoute
  KhaoSatRoute: typeof KhaoSatRoute
  LoginRoute: typeof LoginRoute
  NghiaTrangRoute: typeof NghiaTrangRoute
  PhanTichRoute: typeof PhanTichRoute
  ThamDinhRoute: typeof ThamDinhRoute
  TraCuuRoute: typeof TraCuuRoute
  HoSoIdRoute: typeof HoSoIdRoute
  HoSoIndexRoute: typeof HoSoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-tra': {
      id: '/chi-tra'
      path: '/chi-tra'
      fullPath: '/chi-tra'
      preLoaderRoute: typeof ChiTraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-gia': {
      id: '/danh-gia'
      path: '/danh-gia'
      fullPath: '/danh-gia'
      preLoaderRoute: typeof DanhGiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieu-duong': {
      id: '/dieu-duong'
      path: '/dieu-duong'
      fullPath: '/dieu-duong'
      preLoaderRoute: typeof DieuDuongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dung-cu-chinh-hinh': {
      id: '/dung-cu-chinh-hinh'
      path: '/dung-cu-chinh-hinh'
      fullPath: '/dung-cu-chinh-hinh'
      preLoaderRoute: typeof DungCuChinhHinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/he-thong': {
      id: '/he-thong'
      path: '/he-thong'
      fullPath: '/he-thong'
      preLoaderRoute: typeof HeThongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khao-sat': {
      id: '/khao-sat'
      path: '/khao-sat'
      fullPath: '/khao-sat'
      preLoaderRoute: typeof KhaoSatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nghia-trang': {
      id: '/nghia-trang'
      path: '/nghia-trang'
      fullPath: '/nghia-trang'
      preLoaderRoute: typeof NghiaTrangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phan-tich': {
      id: '/phan-tich'
      path: '/phan-tich'
      fullPath: '/phan-tich'
      preLoaderRoute: typeof PhanTichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tham-dinh': {
      id: '/tham-dinh'
      path: '/tham-dinh'
      fullPath: '/tham-dinh'
      preLoaderRoute: typeof ThamDinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tra-cuu': {
      id: '/tra-cuu'
      path: '/tra-cuu'
      fullPath: '/tra-cuu'
      preLoaderRoute: typeof TraCuuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so/': {
      id: '/ho-so/'
      path: '/ho-so'
      fullPath: '/ho-so/'
      preLoaderRoute: typeof HoSoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so/$id': {
      id: '/ho-so/$id'
      path: '/ho-so/$id'
      fullPath: '/ho-so/$id'
      preLoaderRoute: typeof HoSoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChiTraRoute: ChiTraRoute,
  DanhGiaRoute: DanhGiaRoute,
  DieuDuongRoute: DieuDuongRoute,
  DungCuChinhHinhRoute: DungCuChinhHinhRoute,
  HeThongRoute: HeThongRoute,
  KhaoSatRoute: KhaoSatRoute,
  LoginRoute: LoginRoute,
  NghiaTrangRoute: NghiaTrangRoute,
  PhanTichRoute: PhanTichRoute,
  ThamDinhRoute: ThamDinhRoute,
  TraCuuRoute: TraCuuRoute,
  HoSoIdRoute: HoSoIdRoute,
  HoSoIndexRoute: HoSoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
